name: 'Generate Docs'
on:
  workflow_dispatch:

jobs:
  docs:
    permissions:
      contents: write
    uses: ntatschner/tcs-shared-workflows/.github/workflows/powershell-docs.yml@main
    with:
      module_name: 'tcs.core'
      module_path: 'module/tcs.core'